# Generated by Django 4.0.4 on 2022-05-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measure_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
