# Generated by Django 4.0.4 on 2022-05-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_alter_measurement_sensor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
