# Generated by Django 4.0.4 on 2022-05-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0011_rename_sensor_id_measurement_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor',
            new_name='sensor_id',
        ),
    ]
